### ISSUE TITLE
Upgrade Rails and Ruby

### ISSUE THREAD

**Issue by hpjaj** [oddballio/magnifier#13]
## Background

Let's use the most current, stable versions of Rails and Ruby.

## Definition of done

- [x] Upgrade to Rails 5.2
- [x] Upgrade to Ruby 2.5

**Comment by kfrz** [comment]
@hpjaj to confirm your inquiry from 10/10/18 - `secrets.yml` is removed in Rails 5.2+. Credentials are added with `bin/rails credentials:edit` command. I've started a [wiki page](https://github.com/oddballio/magnifier/wiki/Encrypted-Credentials) to cover some tidbits around handling credentials.
