### ISSUE TITLE
Implement an initial GraphQL server in Ruby

### ISSUE THREAD

**Issue by hpjaj** [oddballio/magnifier#15]
## Background

Once we have started saving all of the GitHub and JIRA data in our database, we will want to offer up that data to our FE through a GraphQL server.

Here is a graphql-ruby tutorial for reference:  https://www.howtographql.com/graphql-ruby/0-introduction/

## Definition of done

- [ ] An outline of the process
- [ ] Create all of the atomic issues ([in GitHub](https://github.com/oddballio/magnifier/issues)) that represent the implementation of the GraphQL server in Ruby

**Comment by RobAWilkinson** [comment]
FYI, that tutorial is pretty out of date, most of the commands are good for initial install. I found: http://graphql-ruby.org/schema/class_based_api.html to be a good resource for the new syntax
