### ISSUE TITLE
Set up prettier to autoformat js files on save

### ISSUE THREAD

**Issue by RobAWilkinson** [oddballio/magnifier#19]
## Background
Rather than deal with the hassles of manually linting, set up [prettier](https://github.com/prettier/prettier) w/ eslint and provide instructions on how to autoformat on save.

Include in the same PR running it across all JS files
 
## Definition of Done
 
 - [x] Prettier set up w/ eslint
-  [x] Clean report from running eslint

**Comment by kfrz** [comment]
Closed, verified eslint + prettier setup
