### ISSUE TITLE
Secure a domain

### ISSUE THREAD

**Issue by hpjaj** [oddballio/magnifier#22]
## Background

We will need to purchase a domain name for the app's deployment.
 
## Definition of Done
 
- [ ] Collaborate with the team on available domain names
- [ ] Work with @RobAWilkinson to purchase a domain

**Comment by RobAWilkinson** [comment]
Subdomain? I have everything in route53

**Comment by hpjaj** [comment]
That works, for sure, and keeps us moving.  We can always move it later if we choose to.

**Comment by kfrz** [comment]
Subdomain is entirely sufficient. `magnifier.oddball.io`?

**Comment by RobAWilkinson** [comment]
works with me, ready whenever
