### ISSUE TITLE
Prevent accidental push's to master

### ISSUE THREAD

**Issue by hpjaj** [oddballio/magnifier#25]
## Background

Per human error, someone might mistakenly push changes directly to `master`.
 
## Definition of Done
 
- [ ] Research and implement a protection that prohibit's user's from accidentally pushing directly to `master`

**Comment by kfrz** [comment]
[Branch protection rules](https://github.com/oddballio/magnifier/settings/branches) will:

-  protect merges without green status/reviews
-  disallow `git push -f`
-  prevent deletion of branch

If we want to protect pushing from local to remote we probably want a hook. 

Something like this in `.git/hooks/pre-commit` will prevent committing to `master` altogether.
```sh
#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "master" ]; then
  echo "Please do not commit directly to master"
  exit 1
fi
```

Downside with the hook is it's not something we can just commit to the project repo, each dev would have to have it added locally, unless we used a [symlink strategy](https://stackoverflow.com/a/37861972) or [`shared-git-hooks`](https://github.com/kilianc/shared-git-hooks)
