### ISSUE TITLE
Compare and contrast Apollo with Relay 2.0

### ISSUE THREAD

**Issue by RobAWilkinson** [oddballio/magnifier#35]
## Background
In order to pick a front end graqphql client of choice, we need to discuss pros and cons of both

## Definition of Done
 
- [ ] Document attached to this ticket, and discussed at next group meeting

**Comment by RobAWilkinson** [comment]
Did some research on this and got a relay project connected to a free relay graphql API. Relay has a ton of very specific restrictions and it also requires a special compiler to convert all `graphql` wrapped queries into compiled bytecode. Incredibly powerful but a lot of confusing stuff.

Apollo I have experience in the past, its simpler to get started, but also not as restrictive in terms of how you do things. Relay requires you to define `Fragments` then you create a top-level query that references those fragments for example, the following gist is a single file example of a query that loads a list of employees (creating the network connection removed for brevity): https://gist.github.com/RobAWilkinson/9d11fa26044b900c742a75df765da6b6

**Comment by hpjaj** [comment]
We decided on Apollo \o/
