### ISSUE TITLE
Google Authentication

### ISSUE THREAD

**Issue by RobAWilkinson** [oddballio/magnifier#4]
## Background

In order to allow oddballs to login with their email address, need to set up oauth2 with google.

## Definition of done
- [ ] Backend and front end are configured to allow for oddball to login

**Comment by RobAWilkinson** [comment]
I have an app set up with client_id and client_secret within the oddball google domain, reach out to me on slack if you need those tokens

**Comment by RobAWilkinson** [comment]
Great example of auth workflow on client side: https://reacttraining.com/react-router/web/example/auth-workflow

**Comment by hpjaj** [comment]
Completed in https://github.com/oddballio/magnifier/pull/42
