### ISSUE TITLE
Investigate Zenhub integration

### ISSUE THREAD

**Issue by RobAWilkinson** [oddballio/magnifier#5]

**Comment by kfrz** [comment]
I think Zenhub is a bit of a stretch for an MVP - we should be able to get the basic data we need from Github alone. 

It might be nice post-MVP to have data around how long issues were in a given swimlane, and other cycle analytics.

**Comment by kfrz** [comment]
@RobAWilkinson @hpjaj I propose we close this issue (or send to a backlog) as it's not going to be affecting our MVP. Thoughts?

**Comment by hpjaj** [comment]
Agreed!  GitHub's API will supply us with everything we need for issue tracking/stats.
