### ISSUE TITLE
Integrate Apollo

### ISSUE THREAD

**Issue by RobAWilkinson** [oddballio/magnifier#53]
## Background
Set up apollo client and integrate it with react on the front end
 
## Definition of Done
 
- [ ] apollo is working and can query the api

**Comment by hpjaj** [comment]
@RobAWilkinson - Psyched we're going this direction!

**Comment by RobAWilkinson** [comment]
As part of my first stab on this, I'm wiring the front end up to allow a user to set their access_token, @hpjaj I'm using your mutation setup that you got going for statistics as a model.
Keep bumping up against an error `"Variable token of type String! was provided invalid value",`.
I don't think I'm wiring my query variables into my mutation properly

**Comment by hpjaj** [comment]
Completed in https://github.com/oddballio/magnifier/pull/60
