### ISSUE TITLE
Watcher for running tests

### ISSUE THREAD

**Issue by RobAWilkinson** [oddballio/magnifier#77]
## Background
In order to make it easier to have tests running automatically would be nice to have an automatic test runner.

Is guard still the defacto standard? 
 
## Definition of Done
 
- [ ] test watcher configured and running, instructions in readme

**Comment by hpjaj** [comment]
Yes, guard is muy bueno 👍

**Comment by hpjaj** [comment]
I got this

**Comment by hpjaj** [comment]
completed
